### ISSUE TITLE
Angular9 with ivy is not working

### ISSUE THREAD

**Issue by lonemanotzi** [triniwiz/nativescript-stripe#111]
I was trying to compile my app which has nativescript-stripe for payment with Angular9 ivy and got this error. 
Looking at various comments posted in nativescript-angular-ivy tag, it looks like the final app will be 20-30% less in size and has better performance overall.

****

ERROR in node_modules/nativescript-stripe/angular/nativescript-stripe.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (nativescript-stripe/angular) which declares CreditCardViewModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

1 export declare class CreditCardViewModule {
                       ~~~~~~~~~~~~~~~~~~~~
Executing webpack failed with exit code 2.
****
After I run tns run android --env.aot, the nativescript-stripe.directives.d.ts become

import * as ɵngcc0 from '@angular/core';
export declare class CreditCardViewDirective {
}
export declare const DIRECTIVES: typeof CreditCardViewDirectiv    static ɵfac: ɵngcc0.ɵɵFactoryDef<CreditCardViewDirective, never>;
    static ɵdir: ɵngcc0.ɵɵDirectiveDefWithMeta<CreditCardViewDirective, "CreditCardView", never, {}, {}, never>;
e;

**Comment by RobertGardner** [comment]
I haven't looked at Ivy yet, since it's not yet officially supported by {N}. I found the PR (https://github.com/NativeScript/nativescript-angular/pull/2124) with instructions to try it out. I'll try to get to that next week, but no promises.

Taking a quick look at the compatibility guide, I don't see anything obvious, except that the ns-stripe plugin is compiled with TS 3.4 and Ivy requires 3.7, and it's built with Angular 8 instead of Angular 9. The `CreditCardViewModule` and `CreditCardDirective` classes are pretty trivial, so it's hard to see what may be causing the problem other than version upgrades.

If you would like to clone the repository and update those versions in `package.json` (or ideally go through all the steps listed in the PR above) it would be helpful.

**Comment by standevo** [comment]
After upgrading to TS 3.8.3

```
ERROR in node_modules/nativescript-stripe/angular/nativescript-stripe.directives.d.ts:4:67 - error TS1005: ',' expected.

4 export declare const DIRECTIVES: typeof CreditCardViewDirectiv    static ɵfac: ɵngcc0.ɵɵFactoryDef<CreditCardViewDirective, never>;
                                                                    ~~~~~~
node_modules/nativescript-stripe/angular/nativescript-stripe.directives.d.ts:4:74 - error TS1005: ',' expected.

4 export declare const DIRECTIVES: typeof CreditCardViewDirectiv    static ɵfac: ɵngcc0.ɵɵFactoryDef<CreditCardViewDirective, never>;
                                                                           ~~~~
node_modules/nativescript-stripe/angular/nativescript-stripe.directives.d.ts:5:5 - error TS1128: Declaration or statement expected.

5     static ɵdir: ɵngcc0.ɵɵDirectiveDefWithMeta<CreditCardViewDirective, "CreditCardView", never, {}, {}, never>;
      ~~~~~~
node_modules/nativescript-stripe/angular/nativescript-stripe.directives.d.ts:5:112 - error TS1005: '(' expected.

5     static ɵdir: ɵngcc0.ɵɵDirectiveDefWithMeta<CreditCardViewDirective, "CreditCardView", never, {}, {}, never>;
```

**Comment by RobertGardner** [comment]
@Stanteq Is this report for use with Angular 9 (Ivy)? If so, I haven't tried upgrading yet and don't plan to until {N} officially supports it. You're welcome to try it, though, and submit a PR if you can get it working in both Angular 8 & 9.

If it's for Angular 8 (the plugin uses v8.2) and Typescript 3.8.3, that combination isn't supported since Angular 8.2 requires Typescript version >=3.4.0 and <3.5.0.

**Comment by Stanteq** [comment]
Yes is a report for Angular 9. I just tried to update to see what to expect in the future. I'd prefer the fully Kotlin support more than the Angular 9.

**Comment by triniwiz** [comment]
If you need ivy support please upgrade to `@triniwiz/nativescript-stripe` which uses {N} v7
