### ISSUE TITLE
Cannot read property 'CardInputWidget' of undefined

### ISSUE THREAD

**Issue by marcd123** [triniwiz/nativescript-stripe#12]
**DESCRIPTION**
Trying to use the CreditCardView in an Angular/TypeScript project and an error is thrown when trying to render the component. Seems like there is an issue getting com.stripe.android.view.CardInputWidget from the native android Stripe API. iOS has no issues. Any help is appreciated!

**TNS VERSION**
√ Component nativescript has 4.0.0 version and is up to date.
√ Component tns-core-modules has 4.0.0 version and is up to date.
√ Component tns-android has 4.0.1 version and is up to date.
√ Component tns-ios has 4.0.1 version and is up to date.

**PLATFORM**
Android
(iOS is working perfectly)

**View Code**
`<Page xmlns:stripe="nativescript-stripe">
    <stripe:CreditCardView id="card"/>
</Page>`

**ERROR MESSAGE**
`TypeError: Cannot read property 'CardInputWidget' of undefined`

**CODE CAUSING ERROR**
line 21 in card-view.js of nativescript-stripe/src/android
`this._android = new com.stripe.android.view.CardInputWidget(this._ctx);`

**Comment by marcd123** [comment]
Also getting the error:

`com.stripe.android.Stripe is not a constructor`

which is referenced in this issue:

https://github.com/triniwiz/nativescript-stripe/issues/11

Perhaps there is an underlying issue with the availability of the native android API?

**Comment by triniwiz** [comment]
Fixed https://github.com/triniwiz/nativescript-stripe/commit/4ec277a54a5e18c504eae62c24ac605fad5df963

**Comment by mastashake08** [comment]
Having same issue

**Comment by lukegeaves-ordapad** [comment]
> Having same issue

Me too!

**Comment by RobertGardner** [comment]
With several of these being reported, I looked into it to see if I could reproduce it.

I ran `tns doctor` and made sure my NativeScript environment was up to date.
I got a fresh, clean copy of the plugin from the github repository.
I added my Stripe key to the demo code.
I built and ran first on iOS, then on Android, both the demo and demo-angular apps.

I am building on a Mac and running in iPhone and Android emulators. I use these commands to run:
`npm run demo-angular.ios`
`npm run demo.ios`
`npm run demo-angular.android`
`npm run demo.android`

Both the demo and demo-angular apps run successfully for me, with no errors.

If you can provide steps that reproduce the problem I may be able to help.

(Note: I just noticed that the original bug report says "Trying to use the CreditCardView in an Angular/TypeScript project" but the HTML code provided has
`<Page xmlns:stripe="nativescript-stripe"> <stripe:CreditCardView id="card"/> </Page>`
which is not the correct way to display the CreditCardView in Angular. Instead, follow the example in the demo-angular app:
`<CreditCardView #card></CreditCardView>`
However, since the code in the original post would not work in an Angular project, this is probably not the problem.)

**Comment by lukegeaves-ordapad** [comment]
I thought I would add some more details in here, as I have since managed to get the component working.

**My Environment:**
nativescript v5.2.3
nativescript-vue v2.2.0
nativescript-stripe v5.0.7

**main.js**
```
import Vue from 'nativescript-vue';
...
Vue.registerElement('CreditCardView', () => require('nativescript-stripe').CreditCardView);
...
var app = new Vue({ ...
```

**AddStripeCard.vue**
```
<template>
    <Page class="page" actionBarHidden="true" @loaded="pageLoaded">
        ...
        <CreditCardView id='card'/>
        <Button :text='Save' @tap='verifyStripeCard()'/>
        ...
    <Page>
</template>

<script>
    import { Stripe, Card } from 'nativescript-stripe';
    const stripeAPI = new Stripe('pk_test_123123123123');
    var page = null;
    ...
    
    export default {
        ...
        methods: {
            pageLoaded: function (args) {
                console.log("pageLoaded " + args);
                page = args.object;
            },
            verifyStripeCard: function () {
                var cardObject = page.getViewById("card").card;
                stripeAPI.createToken(cardObject, (error,token) => {
                    if(!error && token){
                        console.log('Stripe token: ' + token);
                        // Then use the token in our API
                    } else {
                        console.log('Stripe Error: ' + error);
                    }
                });
            },        
        }
        ...
    };
</script>
```

I was having the issues described by marcd123, it looked like the parts of the Stripe components where missing from the webpack imported module. Fixed by forcing a clean build, and with the configuration as above. 

I managed to fix this after:
- tns plugin add nativescript-stripe
- delete 'node_modules', 'hooks' and 'platforms' folders 
- tns platform add android
- tns run android --bundle

Hopefully this will help someone with ns-stripe and ns-vue setup
