### ISSUE TITLE
regression: Cannot read property 'CardInputWidget' of undefined

### ISSUE THREAD

**Issue by Maldris** [triniwiz/nativescript-stripe#38]
### Make sure to check the existing issues in this repository 
same error as [#12](https://github.com/triniwiz/nativescript-stripe/issues/12) , which was noted as fixed in [4ec277a](https://github.com/triniwiz/nativescript-stripe/commit/4ec277a54a5e18c504eae62c24ac605fad5df963), possible regression

### Which platform(s) does your issue occur on?
- Android 9 local build running on Pixel 2

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.0.1
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0
- Plugin(s): 5.0.4

### Please, tell us how to recreate the issue in as much detail as possible. 
create page with following xml:
```
<Page xmlns="http://www.nativescript.org/tns.xsd" xmlns:stripe="nativescript-stripe" >
    <StackLayout>
        <Label text="Update your card details:" />>
        <stripe:CreditCardView id="card"/>
        <GridLayout columns="*,auto,auto">
            <Button col="1" text="cancel" tap="close" />
            <Button col="2" text="Update Card" tap="update" />
        </GridLayout>
    </StackLayout>
</Page>
```

navigating to page causes app throws global exception as follows:
```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onCreateView failed

TypeError: Cannot read property 'CardInputWidget' of undefined

StackTrace: 
	Frame: function:'push.../node_modules/nativescript-stripe/stripe.js.CreditCardView.createNativeView', 
	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', 
	...
```

Initially suspected that the stripe android client wasnt imported, looking in the module folder it does have the entry needed in the `include.gradle` file, but the generated `build.gradle` file in my platforms folder does not have the necessary entry:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
the above being the root build.grade in the platforms/android directory, the subsequent file in platforms/android/app doesn't have a reference to stripe either.

**Comment by Maldris** [comment]
as in [#12](https://github.com/triniwiz/nativescript-stripe/issues/12) I also have the secondary exception: `TypeError: com.stripe.android.Stripe is not a constructor`  (which became [#11](https://github.com/triniwiz/nativescript-stripe/issues/12)) when attempting to initialise the package, as my backup plan was to build the ui and invoke the card constructor to tokenise the details.

Hope that helps.

**Comment by RobertGardner** [comment]
I'm not having this problem in my app (I am running on emulator 8.1, API 27). It builds and runs successfully. I am also running CLI 5.0.1, but I'm using the 5.0 versions of the tns-core libraries. (It was a pain upgrading from 4 to 5, though!)

The "Stripe is not a constructor" error sure makes it look like the package `com.stripe.android` is not being loaded, but I suspect that is a build problem, not a plugin problem.

If I look at my `platforms/android/build.gradle` file I also do not see an entry for `com.stripe.android` there, so I'm not sure that's where it's supposed to show up. However, if I search my `platforms/android` folder for `com.stripe` it shows up in a number of places. The most interesting is in `platforms/android/app/build/intermediates/transforms/dexBuilder/debug/__content__.json` where I see `"name":"com.stripe:stripe-android:8.0.0"`.

I don't know enough about the NativeScript Android build system to know if there's a better place to look to make sure it's building correctly. But here are some things to try:

* delete your `node_modules`, `platforms`, `hooks`, and `package-lock.json` files and run `npm i`  (I have an `npm` script that does this since I do it so often), then rebuild
* We recently had to update our Android build tools version to `build-tools-28.0.3`. You might try that.
* Try creating a simple HelloWorld app (using `tns create`) and adding the Stripe card there and see if you have the same problem. That might help you figure out the build problems.

I'm sorry to not have a definitive solution for you, but since I don't have this problem and it looks like a build environment problem, not a plugin problem, I can't figure out what more I can do to help. If you can recreate the problem in the HelloWorld app, that will help me debug. Otherwise, you probably need to take this to NativeScript.

**Comment by Maldris** [comment]
Hi, sorry, I've only just seen your response and its midnight here (I've been busy as Sydney has had record rains today and one of our windows broke).

I'll test those out first thing tomorrow.

I agree it does look like a build issue, I was just unsure what the best option was to resolve it.

I'm very new to nativescript but have a background in android development, which is why I raised the gradle config issue, as building the app normally you would expect the import to be present there, but yes there is a lot that nativescript could be doing under the hood to avoid that.

I'll do more testing in the morning and post any results here.

Thanks for your help Robert.

**Comment by Maldris** [comment]
ok, that appears to have resolved the issue (delete, install and rebuild), but there was some weirdness I experienced that I'll mention here in the event others encounter it.

 - I deleted package-lock.json, node_modules, hooks and platform folders, `npm i` and attempted to rebuild
 - Received an error that the android system string `title_activity_kimera` was missing.
 - Checked my strings.xml file and it was present, resaved the file (no changes) and tried the build again.
 - Instead received errors about the values.xml entries `font`, `fontStyle`, `fontWeight` being missing.
 - Check the file, they are present, resave that file (again without change).
 - Rebuild the project and all works as expected now.

I'll be trying to replicate these issues, and if I'm able to, post about them in the nativescript repo.

Thanks for your help, and sorry for the inconvenience.
