### ISSUE TITLE
InitCustomerSession undefined property 

### ISSUE THREAD

**Issue by benlooi** [triniwiz/nativescript-stripe#39]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
On tested on Android device at the moment

### Please, provide the following version numbers that your issue occurs with:
CLI: 5.0.0
Cross-platform modules : 5.0.5
Runtime: 5.0.0
PLugin: 5.0.4

### Please, tell us how to recreate the issue in as much detail as possible. 
I just copied the Stripe.service.ts example from the demo-angular folder. Once my app hits the page that starts calling on StripeService, the error happens and I cannot proceed.

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'initCustomerSession' of undefined
TypeError: Cannot read property 'initCustomerSession' of undefined
    at new StripeCustomerSession (file:///data/data/co.pompipi.app2018/files/app/tns_modules/nativescript-stripe/standard/standard.js:50:44)

### Is there any code involved? 
 I have implemented backendAPI for ephermeral keys and it is working. 
 ```
public function ephemeral_keys() {
        parse_str($_SERVER['QUERY_STRING'], $params);
       // echo $params['customer'];
        $customerId=$params['customer'];
       $key= \Stripe\EphemeralKey::create(
      ["customer" => $customerId],
      ["stripe_version" => "2018-11-08"]
    );
   
   return json_encode($key);
    
        
    }
```
Here is my OnInit  code. I do not know what the "this" in StripeConfig.shared().backendAPI value is, as the example was "this" but in documentation it says <YOUR_BACKEND_API>.
```
private customerSession: StripeCustomerSession;

  constructor( private userService: UserService) {
    StripeConfig.shared().backendAPI = this;
    StripeConfig.shared().publishableKey = publishableKey;
    //StripeConfig.shared().appleMerchantID = appleMerchantID;
    StripeConfig.shared().companyName = "Pompipi";
    StripeConfig.shared().requiredShippingAddressFields = [StripeShippingAddressField.PostalAddress];

   this.customerSession = new StripeCustomerSession();
  }

  private backendURL(pathComponent: string): string {
    if (!backendBaseURL) throw new Error("backendBaseURL must be set");
    if (!backendBaseURL.endsWith("/")) {
      return backendBaseURL + "/" + pathComponent;
    } else {
      return backendBaseURL + pathComponent;
    }
  }

  createCustomerKey(apiVersion: string): Promise<any> {
    let url = this.backendURL("ephemeral_keys");
    return httpModule.request({
      url: url,
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded; charset=utf-8" },
      content: "api_version=" + apiVersion + "customer="+this.userService.user.clientToken
    }).then(response => {
      console.log(response);
      if (response.statusCode < 200 || response.statusCode >= 300) {
        throw new Error(response.content.toString());
      }
      return response.content.toJSON();
      
    });
  }
```

**Comment by RobertGardner** [comment]
Unfortunately my laptop died so it'll be a week or two before I can take a deeper look at this.

In the code:
`StripeConfig.shared().backendAPI = this;`

`backendAPI` is supposed to be an object that implements the interface `StripeBackendAPI` (declared in `nativescript-stripe/standard/index.d.ts`). In the demo app, `StripeService` implements that interface, so the demo sets `backendAPI` to `this`.

Sorry that wasn't very clear. I'll add a comment in the demo.

Let me know if this fixes your issue. If not, I'll look further.

**Comment by benlooi** [comment]
Hey, thanks for replying so quickly. So let me try to understand so I can see how to fix my problem.
What does newCustomerSession do or require? Does it call createCustomerKey to get the ephermeral_keys generated by my own server? It is undefined, which means I need to pass something to some function? I am looking at the code ,

```
var StripeCustomerSession = (function () {
    function StripeCustomerSession() {
        com.stripe.android.CustomerSession.initCustomerSession(createKeyProvider());
        this.native = com.stripe.android.CustomerSession.getInstance();
    }
    return StripeCustomerSession;
}());
exports.StripeCustomerSession = StripeCustomerSession;
function createKeyProvider() {
    return new com.stripe.android.EphemeralKeyProvider({
        createEphemeralKey: function (apiVersion, keyUpdateListener) {
            StripeConfig.shared().backendAPI.createCustomerKey(apiVersion)
                .then(function (key) {
                keyUpdateListener.onKeyUpdate(JSON.stringify(key));
            }).catch(function (e) {
                keyUpdateListener.onKeyUpdateFailure(500, e);
            });
        }
    });
}
```
Where to I pass the ApiVersion, or how does NewCustomerSession() knows what APIVersion to pass to EphermeralKeyProvider? Hope I make sense....

**Comment by RobertGardner** [comment]
`initCustomerSession` is a function on the Stripe API's `CustomerSession` object. If that is undefined, it suggests that the Stripe SDK is not installed. I assume you used `npm install nativescript-stripe` to install the package. 

I suggest you delete `node_modules` and `package-lock.json` and rebuild.

`apiVersion` is provided by the Stripe SDK and passed to `createEphemeralKey` by the SDK when it calls `createEphemeralKey`. That method calls an Android handler that eventually calls the `StripeBackendAPI` that is set in`backendAPI`. However, the error message suggests it's not even getting that far because  `com.stripe.android.CustomerSession` is undefined. That class is part of the Stripe SDK, which should be downloaded and installed during the build process.

As mentioned, not having access to my build system makes it hard for me to dig deeper or give better info. I hope this helps and again, if not I'll keep trying. 😃

**Comment by benlooi** [comment]
Ah, yes. Forgot about the rebuilding. Thanks for the explanation.

**Comment by benlooi** [comment]
> `initCustomerSession` is a function on the Stripe API's `CustomerSession` object. If that is undefined, it suggests that the Stripe SDK is not installed. I assume you used `npm install nativescript-stripe` to install the package.
> 
> I suggest you delete `node_modules` and `package-lock.json` and rebuild.
> 
> `apiVersion` is provided by the Stripe SDK and passed to `createEphemeralKey` by the SDK when it calls `createEphemeralKey`. That method calls an Android handler that eventually calls the `StripeBackendAPI` that is set in`backendAPI`. However, the error message suggests it's not even getting that far because `com.stripe.android.CustomerSession` is undefined. That class is part of the Stripe SDK, which should be downloaded and installed during the build process.
> 
> As mentioned, not having access to my build system makes it hard for me to dig deeper or give better info. I hope this helps and again, if not I'll keep trying. 😃

Error resolved. Yup, rebuilding helped. Thanks.

**Comment by benlooi** [comment]
Hi. It's me again. I fixed that error, but now I am getting another error in OnInit when I create a payment session as per the demo example.

My app crashes  with the error : Calling js method OnPaymentSessionDataChanged failed. Cannot read property 'getType' of null , standard.js line 138.

any idea? Cos I do not understand the parameters, this.page, this.total, new Listener(this). 2nd and 3rd argument is ok, I'm not sure what this.page does.

My API version on Stripe is the latest 2018-11-08, and the API version passed by the plugin is 2017-06-05. Does it make a difference?

**Comment by RobertGardner** [comment]
`this.page` is a NativeScript `Page` object, injected into the Component's constructor. You can see it injected on line 21 of `standard.component.ts`.

However, it looks like a different problem. The error suggests that `source` is null in the `createPaymentMethod` function. `source` comes from the Stripe API's `customer` and indicates what type of payment method is being used. This was a part of the Stripe API that is not well documented and it's possible that changed in the newest revision of the Stripe API. I'd have to do some debugging to figure that out, which I won't be able to do for a week or two.

In the meantime, can you try it with the 2017-06-05 version of Stripe API? (in build.gradle use `com.stripe:stripe-android:8.0.0`) I don't know if you're relying on anything in the 8.1.0 version of `stripe-android`, but if not this will help me understand what's going on.

**Comment by RobertGardner** [comment]
I was looking at this more closely and I don't think the API version is the problem. Instead, it looks like you may be trying to create the `PaymentSession` before you've created a `CustomerSession`.

The `CustomerSession` in the demo is created in `StripeService`'s constructor. You need to make sure that `StripeService` has been constructed several ticks before you call `createPaymentSession()` since some of the creation process is asynchronous. In demo-angular, this is done with dependency injection (`StripeService` is injected into the `StandardComponent` class).

So, if you are using Angular, you must have a component that is going to display the Stripe dialogs. Inject a `Page` and a `StripeService` into that component. Then in that component's `ngOnInit` you should be able to call `stripeService.createPaymentSession()`. Also, make sure that `StripeService` is declared in one of your modules as a `provider` so that it can be injected.

Finally, as a debugging aid, you might want to copy all the files in `demo-angular/app/demo` into your app, provide a button somewhere that takes you to the `home` component, and make sure the Standard Demo page is able to bring up the Stripe dialogs. If they are, you can then work from there to your own app to get it working. If the demo page is not bringing up the Stripe dialogs, knowing that you are using the demo-angular pages will make it easier for me to diagnose the problem.

**Comment by RobertGardner** [comment]
I got my laptop back! Anything I can do to help?

My process in my own app was:

* Copy `stripe.service.ts` from `demo-angular/app/demo` to my app and wire it into my services (add it to a `provider`, etc). Other than the constants at the top, I didn't change any code in the service.
* Copy the form from `demo-angular/app/demo/standard.component.html` (everything below the ActionBar) into the page where I wanted the payment dialogs to appear.
* Go through the form to find everything that is dynamically built (usually indicated by `[]` around an HTML property or a method call) and copy the code for that element from `demo-angular/app/demo/standard.component.ts` into my own `.component.ts`. (This was basically copying the entire `standard.component.ts` but I did it this way to fold it into my existing component. I could have also done it the other way, starting with `standard.component.ts` and adding the stuff for my app into it.)

I had to navigate to the page a time or two to make sure I had copied everything correctly, but it went quickly and worked without problem.

By the way, if you are not using Angular, you might find the code in `demo` more similar to your own code. It works exactly the same as `demo-angular` but uses NativeScript core.

**Comment by benlooi** [comment]
Hi Robert,
Getting a different error now, still no luck. Seems to be having problem with retrieving current customer from Stripe. Error reported on Standard.js line 138. 
Am I doing it wrong with my CreateCustomerKey call? This is what I am getting from my server:

(console logged the API callback)
{
  "id": "ephkey_1Dje1EDxvzqf20tqkb6qHU3r",
  "object": "ephemeral_key",
  "associated_objects": [
    {
      "id": "cus_xxxxxxxxxxW2ukI",
      "type": "customer"
    }
  ],
  "created": 1545360344,
  "expires": 1545363944,
  "livemode": false,
  "secret": "ek_test_xxxxxxxxxxxxxxxxLDk1NXpIYk9kcHhCMnZtQkZ5TEJKbDZvaxxxxxxxxx"
}

I am using angular.

**Comment by RobertGardner** [comment]
standard.js line 138 is where errors are reported that are received from the backend when the payment result is being returned. It calls the listener's onError() to return the error message. What error are you receiving?

Did you use the sample backend at https://github.com/stripe/example-ios-backend and deploy it to Heroku? If not, you could try that to make sure your frontend code is working correctly since that backend is known to work with the demo app.

In my own app (not the demo, but the production app I'm working on), my CreateCustomerKey call sends this http request (see below about why there's customer_id & user_id fields -- they're optional):
```
Domain: https://rg-example-stripe-backend.herokuapp.com/ephemeral_keys
Query String: api_version=2015-10-12&customer_id=cus_EA0LxxxxxAmXXX&user_id=NFCw4XXXXXXXUQTVEzs8mKxxxxxx
```

and gets this response:
```
{
"id":"ephkey_1Djc8iEkJak2tlltgXQARUX3",
"object":"ephemeral_key",
"associated_objects":[{"id":"cus_EA0LxxxxxAmXXX","type":"customer"}],
"created":1545353120,
"expires":1545356720,
"livemode":false,
"secret":"ek_test_YWNxxxxxxxxxx05Fa0phazJ0bGx0LHpxeGpvYlJ4Sm9JNEpOcmZndGpmWTJZXXXXXXXXXX"
}
```

which looks very similar to what you are getting.

So it doesn't look like the problem is with creating the customer.

I have found a number of different errors can happen when working with the Stripe backend API and you have to be careful. The error message should provide more information if you can capture that and log it (I set it into a component property and display it on the payment page, you might also get more info by looking at the Heroku log files). One error I used to run into a lot was using one customer ID to create the payment source (the credit card) and a different customer ID to charge the card. This was happening because the sample backend creates a new customer ID on every call to the API. It's not robust but is intended just for demo purposes and supports the interaction for the simple demo, but is not what you'd use in a real application. In my case, I slightly modified the backend so I could pass the customer ID to the backend so I'd use a consistent customer ID on every call. I store the Stripe customer ID with my own application's user ID. When I make Stripe calls, I use that stored customer ID on all the calls.

I can send you the updates I made to the sample backend, but they are not robust and are a work in progress. I manually copy the customer ID into my (firebase) database. Eventually I'd like to have the backend store the customer ID into the firebase user, but I'm not there yet.

I am discovering that getting the Stripe UI to show up in my mobile app is just half the battle. Writing a robust Stripe backend is also looking to be a bit of an ordeal, which is probably true no matter what frontend you write for or what payment processing system you use.. Maybe when I get further along I'll add a more robust backend to the nativescript-stripe project. In the meantime, keep asking questions and I'll see what I can do to help.

One final note: I typically work on iOS. It's possible there are problems on Android that I'm missing because I only do cursory Android checks. I'll try on Android again to make sure it's still working OK.

**Comment by benlooi** [comment]
Hey, I just checked my Stripe test data and it did receive the api call for customer info. However the response body is empty. So I guess it is not a problem with your back-end. Hmm. Maybe the older API version is the issue. I try to hardset the latest version in my call.

**Comment by RobertGardner** [comment]
It's worth a try, but I'm not convinced that's the problem. As you can see, I'm using `api_version=2015-10-12` so the older version works. You need to use the same version in the frontend and backend, but the Stripe system takes care of that. I never actually set the api_version anywhere.

The sample backend was actually written by Stripe, not by me. You should follow the instructions in stripe.service.ts to create your own copy. The copy currently at rg-example-stripe-backend.herokuapp.com has been modified and no longer works correctly with the demo app in nativescript-stripe.

**Comment by benlooi** [comment]
I viewed test data on Stripe and the request body is blank, and so is the response body, for the GET calls to /v1/customers/CUSTOMER_ID.  The calls to ephemeral_keys has data for the request and response body, so I guess that's where the problem lies. The logs show 200 ok status for the calls. Will poke around some more.

UPDATE: 
The stacktrace error message when my app crashes indicates a problem with createPaymentMethod function. cannot read property getType of null. I think the variable "source" is the issue. Error reporting line 218 in standard js,and subsequently line 140 (onCustomerRetrieved), then line 138. Advise?

**Comment by RobertGardner** [comment]
OK, this is looking more like one of the earlier problems you had. This is in an area of the Stripe Android SDK that is not well documented, so I may not be using the API correctly.

The good news (sort of...) is that I just tried this on Android on my real app (not the nativescript-stripe demo) and I'm getting the same crash. So now I can fix it on my end. Hopefully I'll have that done in a few hours.

Thank you for your patience, and sorry for the problems you're having!

**Comment by benlooi** [comment]
Thanks for fixing this. Works now on both IOS and Android.
