### ISSUE TITLE
EU Strong Customer Authentication support integration

### ISSUE THREAD

**Issue by marayfirth** [triniwiz/nativescript-stripe#45]
With the upcoming PSD2 regulation for Europe market, Stripe is adding more features like PaymentIntents. It would be nice to support it before the law goes live and many payments get refused.
More info here: https://stripe.com/payments/strong-customer-authentication

**Comment by RobertGardner** [comment]
I looked at this and it appears Stripe doesn't have their mobile SDKs ready for this, based on this comment in their PaymentIntents section:

> With the iOS and Android PaymentIntents integrations, you can open the redirect URL in a native browser or in-app web view so the customer can complete authentication. In the coming months, we’ll also offer a native, customizable 3D Secure integration with our mobile SDKs.

Also, I couldn't find instructions on how the mobile "Standard Integration" should be updated (if at all) to support PaymentIntents. The "Custom Integration" this plugin supports only collects credit card tokens and leaves the payment implementation up to the developer, so in that case there is nothing we'd be able to do to help with this migration. 

If you have more information and would like to propose specific changes to the plugin to support Strong Customer Authentication, we'd be happy to review your Pull Requests. :-)

**Comment by sebj54** [comment]
Hi there!

As a EU developer, I'm concerned about the Strong Customer Authentication too.

I read the docs about PaymentIntents (https://stripe.com/docs/payments/payment-intents/migration) and it seems that this plugin should at least create a `PaymentIntentParams` with a `Source`: https://stripe.com/docs/payments/payment-intents/android#handle-card-payment.

This is necessary to use PaymentIntents with a credit card form (to confirm the payment intent).

According to the documentation, SDKs are ready for 3D Secure. Only the redirect is up to the developer (https://stripe.com/docs/payments/payment-intents/android#handle-authentication). They will update their SDKs to handle the redirection in the SDK.

Since it is a NativeScript plugin, couldn't we show the redirect page in a WebView?

Thanks for your help on this, I'm new to the world of NativeScript so pardon me if I missed anything!
