### ISSUE TITLE
CC payments not working on physical android

### ISSUE THREAD

**Issue by rynop** [triniwiz/nativescript-stripe#55]
`demo-angular` working fine on iOS (phys&emu) as well as Android emulator (Galaxy Nexus API v28, Android v9.0).

When I run the Standard integration demo on a physical android device (specs below) I get the following error:

```
JS: Error (100) error: Error: Error: The Source src_XXX does not belong to the Customer you supplied cus_YYY. Please use this Source with the Customer that it belongs to instead.**
```

I get this error dumped from the `onError()` method in `standard.components.ts` (I added error logging - see below)

Here is the error I see in Heroku (note the HTTP `402`):

```
2019-04-23T15:20:27.773125+00:00 heroku[router]: at=info method=POST path="/capture_payment" host=ns-stripe-payment-intent.herokuapp.com request_id=69fcefd5-1c0b-4116-b024-76bc1d19b6e5 fwd="71.37.201.101" dyno=web.1 connect=0ms service=614ms status=402 bytes=817 protocol=https
2019-04-23T15:20:27.770126+00:00 app[web.1]: 71.37.201.101 - - [23/Apr/2019:15:20:27 +0000] "POST /capture_payment HTTP/1.1" 402 180 0.6110
2019-04-23T15:20:27.770637+00:00 app[web.1]: 10.69.234.140 - - [23/Apr/2019:15:20:27 UTC] "POST /capture_payment HTTP/1.1" 402 180
2019-04-23T15:20:27.770792+00:00 app[web.1]: - -> /capture_payment
```

At first I thought the customer object was hard-coded in the `stripe/example-ios-backend`, however a [new customer is created every time](https://github.com/stripe/example-ios-backend/blob/master/web.rb#L86).

### Which platform(s) does your issue occur on?

Android, OnePlus 3, Android version: 8.0.0

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.3.2
- Cross-platform modules: 5.3.1
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): https://github.com/triniwiz/nativescript-stripe/blob/master/demo-angular/package.json

### Please, tell us how to recreate the issue in as much detail as possible. 

1.  Launch https://github.com/stripe/example-ios-backend
1.  Connect physical android device
1.  `tns run android`
1.  run the Standard integration demo, add card (...4242), shipping info and hit `Buy` button

### Is there any code involved? 

https://github.com/triniwiz/nativescript-stripe/blob/master/demo-angular and modified `standard.components.ts` to dump error:

```typescript
  onError(_errorCode: number, message: string) {
    console.error(`Error (${_errorCode})`,message);  // Added this line only
    this.component.errorMessage = message;
    this.component.changeDetectionRef.detectChanges();
  }
```

**Comment by RobertGardner** [comment]
That's really wild. I can't figure out why it would be different on the hardware than on the emulator.

I suggest you log all the calls to and from the backend server, in `stripe.service.ts` and make sure the call sequences are identical between hardware and emulator. If you can, log all the cookies in addition to the parameters.

Another way to verify this, if you want to work at that level (in Ruby), is to edit the backend's `web.rb` to log the results of the `authenticate` method to indicate what user it is identifying.

The only thing I can think of is that cookie management on the two is different and the backend session state in the server is not being maintained on the hardware device. (The backend server determines the user from a session cookie.) In my own implementation of the backend, I have the mobile app pass the customer ID to the backend instead of using a session cookie.

If this turns out to be the case, then the plugin is working correctly. It's possible there's something that needs to be done in the demo app to fix this, though. (I don't know anything about Android development and don't have Android hardware to test it on. I sure appreciate you doing this!)

**Comment by rynop** [comment]
Totally agree on strange. 10-4 on `stripe.service.ts` logging everything to track cadence.

I actually got it working last night, with no code changes (server or app side).  My initial hunch is some session quirk.  Right away I tried debugging on the Heroku side, but I can't get it to log.  [Issue opened](https://github.com/stripe/example-ios-backend/issues/51).  From what I can tell it should be [logging everything](https://github.com/stripe/example-ios-backend/blob/master/web.rb#L62), but its not.  I'm not good with Ruby so any experience you may have here would be appreciated.

I'm going to be writing my own backend here very soon, so I'll keep this open in the case I can consistently reproduce it with my backend.   Like you, I was not planning on relying on cookie device side, so I may not run into it :) In either case I'll report back here.
