### ISSUE TITLE
SCA intents questions

### ISSUE THREAD

**Issue by carlosanjos** [triniwiz/nativescript-stripe#79]
### Which platform(s) does your issue occur on?
Both platforms
* Android 7.1.1 Nexus 6
* iPhone 6 Plus iOS 12.3.1

### Please, provide the following version numbers that your issue occurs with:
```
tns --version
5.4.2
```

```
 "tns-android": {
      "version": "5.4.0"
    },
    "tns-ios": {
      "version": "5.4.2"
    }
```
---
I understood from Stripe docs [https://stripe.com/docs/payments/cards/saving-cards#saving-card-without-payment] I(https://stripe.com/docs/payments/cards/saving-cards#saving-card-without-payment) I need to create a payment intent on the server. Then pass the intent to the Stripe SDK. Then collect the payment card info and finally confirm the intent to finish the flow.

In {N} I tried the following, using the payment card number **4000 0000 0000 3220** expiry date **02/22** CVC **222**
```typescript
constructor() {
    this.stripe = new Stripe('pk_test_MY_KEY');
}
```

```typescript
public saveCard(cardView: CreditCardView): void {
    if (cardView.card) {
       this.stripe.createPaymentMethod(cardView.card, (error, paymentMethod) => {
           const clientSecret: string =  "seti_1F2Fl7IQbGBBlh2WTPElUlXV_secret_FXKP24aPmuwPkqZrIBO6mmqOS5OtwcW";

           if (error) {
              console.log(error);
              return;
           }

          const intentParms: StripePaymentIntentParams =  new StripePaymentIntentParams();
          intentParms.clientSecret = clientSecret;
          intentParms.paymentMethodId = paymentMethod.id;
          const paymentIntent = StripePaymentIntent.fromNative(intentParms.native);
          console.log(`Payment intent ${paymentIntent.clientSecret}`);
          this.stripe.confirmPaymentIntent(paymentIntent, '', (error, stripePaymentIntent) => {
               console.log(`----------------Errors ${error}----------------------`);
               console.log(stripePaymentIntent)
          });
       });
     }
 }
```
On Android it won't create a payment method at all. It always returns the error `Error`
On iOS [Code=50 “No such payment_intent” when confirm payment intent for stripe](https://stackoverflow.com/questions/56610256/code-50-no-such-payment-intent-when-confirm-payment-intent-for-stripe)

What am I missing?

**Comment by RobertGardner** [comment]
The version of the Android Stripe SDK currently used by this plugin does not support `createPaymentMethod()` since it can't be called on the UI thread. There is an effort underway (see #78 ) to update the Android Stripe SDK, which should fix this.

Unfortunately, I have not used payment intents so am unable to provide any help (I may get to it in a few weeks). I take it the client secret you are using was generated on the server? Can you see the Payment Intent in the Stripe dashboard? Are both client and server using the same PK Key? Those are the only things I can think of right now. If you learn more, please update this bug so others will learn from your experience.
