### ISSUE TITLE
v5.5.0

### ISSUE THREAD

**Issue by triniwiz** [triniwiz/nativescript-stripe#82]
`5.5.0` should be a major release if it is not compatible with any previous {N} .... so it should be `6.0.0`

**Comment by RobertGardner** [comment]
The author (@jeremypele) and I discussed this and concluded that since the plugin API didn't change, a minor version bump was appropriate. We think it works with previous {N} but neither of us was able to test it to make sure.

Jeremy is working on a very large update that adds support for Strong Customer Authentication. That one will be v6.0.0. It's now in testing and should be published in a week or so.

**Comment by triniwiz** [comment]
Sounds good 🙂 keep up the good work
